versions:
  "3.81":
    platforms: *base_platforms
    build_args:
      PLATFORMSH_CLI_VERSION: "3.81.0"
      PLATFORMSH_CLI_SHASUM: "3960b1cf697cb6d6c076bf02d4f5b7d0dcf2cdd9511ca75694545f29b86316e6"
    test_config:
      cmd:
        - php --version
        - platform --version
        - python --version
        - pip --version
