versions:
  "2":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config:
      cmd:
        - az --version
        - git --version
        - helm diff version
        - helm version
        - kustomize version
        - pip --version
        - pipenv --version
        - trivy --version
        - terragrunt --version
        - infracost --version
        - tfenv init
        - unzip -v
        - zip --version
        - kubectl version --client
