sudo: required
dist: xenial
language: python
python: 3.6

services:
  - docker

before_install:
  - pip install pip pipenv
  - pipenv sync

matrix:
  include:
    - env: IMAGE=ansible VERSION=2.5.5
    - env: IMAGE=arachni VERSION=1.5
    - env: IMAGE=aws VERSION=1
    - env: IMAGE=awslnx-systemd VERSION=2
    - env: IMAGE=chrome VERSION=1
    - env: IMAGE=dind-aws VERSION=1
    - env: IMAGE=golang VERSION=1.11
    - env: IMAGE=java VERSION=6
    - env: IMAGE=java VERSION=8
    - env: IMAGE=java VERSION=11
    - env: IMAGE=kubectl VERSION=1.15
    - env: IMAGE=node VERSION=6.17
    - env: IMAGE=node VERSION=8.16
    - env: IMAGE=node VERSION=10.15
    - env: IMAGE=php VERSION=7.1
    - env: IMAGE=php VERSION=7.2
    - env: IMAGE=python VERSION=2.7
    - env: IMAGE=python VERSION=3.7
    - env: IMAGE=react-native VERSION=1
    - env: IMAGE=ruby VERSION=2.6
    - env: IMAGE=scoutsuite VERSION=5.2
    - env: IMAGE=serverless VERSION=1.48
    - env: IMAGE=sonar VERSION=3.3
    - env: IMAGE=terraform VERSION=0.12

script:
  - travis_wait pipenv run python travis.py build --image ${IMAGE} --version ${VERSION}
