sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node     VERSION=6.11 MODD_VERSION=0.4 NODE_VERSION=6.11.3
    - env: LANGUAGE=node     VERSION=7.10 MODD_VERSION=0.4 NODE_VERSION=7.10.1
    - env: LANGUAGE=node     VERSION=8.6  MODD_VERSION=0.4 NODE_VERSION=8.6.0
    - env: LANGUAGE=java     VERSION=8    MODD_VERSION=0.4 JAVA_VERSION=8u144-1~webupd8~0
    - env: LANGUAGE=php      VERSION=5.3  MODD_VERSION=0.4 PHP_VERSION=5.3.10 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.4
    - env: LANGUAGE=php      VERSION=5.6  MODD_VERSION=0.4 PHP_VERSION=5.6.31 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.4
    - env: LANGUAGE=php      VERSION=7.1  MODD_VERSION=0.4 PHP_VERSION=7.1.9  PHP_BUILD_INSTALL_EXTENSION=apcu=5.1.8  REDIS_VERSION=3.1.4
    - env: LANGUAGE=aws      VERSION=1
    - env: LANGUAGE=dind-aws VERSION=1    DOCKER_COMPOSE_VERSION=1.16.1
    - env: LANGUAGE=golang   VERSION=1.9  MODD_VERSION=0.4 GLIDE_VERSION=v0.13.0
    - env: LANGUAGE=ruby     VERSION=2.4
    - env: LANGUAGE=ansible  VERSION=2.3.2 ANSIBLE_VERSION=2.3.2

script:
    - travis_wait python travis.py
