sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node     VERSION=4.7 MODD_VERSION=0.4 NODE_VERSION=4.7.3
    - env: LANGUAGE=node     VERSION=6.9 MODD_VERSION=0.4 NODE_VERSION=6.9.5
    - env: LANGUAGE=node     VERSION=7.5 MODD_VERSION=0.4 NODE_VERSION=7.5.0
    - env: LANGUAGE=java     VERSION=8   MODD_VERSION=0.4 JAVA_VERSION=8u121-1~webupd8~2
    - env: LANGUAGE=php      VERSION=5.6 MODD_VERSION=0.4 PHP_VERSION=5.6.30 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.1
    - env: LANGUAGE=php      VERSION=7.1 MODD_VERSION=0.4 PHP_VERSION=7.1.1 PHP_BUILD_INSTALL_EXTENSION=apcu=5.1.8 REDIS_VERSION=3.1.1
    - env: LANGUAGE=aws      VERSION=1
    - env: LANGUAGE=dind-aws VERSION=1
    - env: LANGUAGE=golang   VERSION=1.7 MODD_VERSION=0.4 GLIDE_VERSION=v0.12.3

script:
    - python travis.py
