sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node     VERSION=6.11 MODD_VERSION=0.4 NODE_VERSION=6.11.1
    - env: LANGUAGE=node     VERSION=7.10 MODD_VERSION=0.4 NODE_VERSION=7.10.1
    - env: LANGUAGE=node     VERSION=8.2  MODD_VERSION=0.4 NODE_VERSION=8.2.1
    - env: LANGUAGE=java     VERSION=8    MODD_VERSION=0.4 JAVA_VERSION=8u144-1~webupd8~0
    - env: LANGUAGE=php      VERSION=5.3  MODD_VERSION=0.4 PHP_VERSION=5.3.10 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.3
    - env: LANGUAGE=php      VERSION=5.6  MODD_VERSION=0.4 PHP_VERSION=5.6.31 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.3
    - env: LANGUAGE=php      VERSION=7.1  MODD_VERSION=0.4 PHP_VERSION=7.1.7  PHP_BUILD_INSTALL_EXTENSION=apcu=5.1.8  REDIS_VERSION=3.1.3
    - env: LANGUAGE=aws      VERSION=1
    - env: LANGUAGE=dind-aws VERSION=1    DOCKER_VERSION=17.09.0~ce-0~ubuntu DOCKER_COMPOSE_VERSION=1.16.1
    - env: LANGUAGE=golang   VERSION=1.8  MODD_VERSION=0.4 GLIDE_VERSION=v0.12.3
    - env: LANGUAGE=ruby     VERSION=2.4

script:
    - python travis.py
