sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node VERSION=4.6
    - env: LANGUAGE=node VERSION=6.9
    - env: LANGUAGE=node VERSION=7.0
    - env: LANGUAGE=java VERSION=8
    - env: LANGUAGE=php  VERSION=5.6
    - env: LANGUAGE=php  VERSION=7.0

script:
    - python travis.py