sudo: required
dist: trusty
language: python

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node     VERSION=6.12 NODE_VERSION=6.12.3 NPM_VERSION=3.10.10
    - env: LANGUAGE=node     VERSION=8.9  NODE_VERSION=8.9.4  NPM_VERSION=5.6.0
    - env: LANGUAGE=node     VERSION=9.4  NODE_VERSION=9.4.0  NPM_VERSION=5.6.0
    - env: LANGUAGE=java     VERSION=8    JAVA_VERSION=8u161-1~webupd8~0
    - env: LANGUAGE=php      VERSION=5.3  PHP_VERSION=5.3.10 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.6 SECURITY_CHECKER_VERSION=2.0.6
    - env: LANGUAGE=php      VERSION=5.6  PHP_VERSION=5.6.33 PHP_BUILD_INSTALL_EXTENSION=apcu=4.0.11 REDIS_VERSION=3.1.6 SECURITY_CHECKER_VERSION=4.1.6
    - env: LANGUAGE=php      VERSION=7.2  PHP_VERSION=7.2.1  PHP_BUILD_INSTALL_EXTENSION=apcu=5.1.9  REDIS_VERSION=3.1.6 SECURITY_CHECKER_VERSION=4.1.7
    - env: LANGUAGE=aws      VERSION=1
    - env: LANGUAGE=dind-aws VERSION=1    DOCKER_COMPOSE_VERSION=1.18.0
    - env: LANGUAGE=golang   VERSION=1.9  GLIDE_VERSION=v0.13.1
    - env: LANGUAGE=ruby     VERSION=2.5
    - env: LANGUAGE=ansible  VERSION=2.3.0.0-r1 PYTHON_VERSION=2.7.13-r1 GLIBC_VERSION=2.26-r0
    - env: LANGUAGE=sonar    VERSION=3.0  SONARSCANNER_VERSION=3.0.3.778

script:
    - travis_wait python travis.py
