sudo: required
dist: trusty
language: go

services:
  - docker

matrix:
  include:
    - env: LANGUAGE=node VERSION=4.6
    - env: LANGUAGE=node VERSION=6.9
    - env: LANGUAGE=node VERSION=7.0
    - env: LANGUAGE=java VERSION=8
    - env: LANGUAGE=php  VERSION=5.6
    - env: LANGUAGE=php  VERSION=7.0

script:
    - echo "Checking changed files (${TRAVIS_COMMIT_RANGE/.../..})"
    - FILES=`git diff --name-only ${TRAVIS_COMMIT_RANGE/.../..} | sort | uniq`
    - if [[ $FILES == *"${LANGUAGE}${VERSION}"* ]]; then docker build -t ${LANGUAGE}${VERSION} --no-cache ${LANGUAGE}${VERSION}; fi
    - if [[ $FILES == *"${LANGUAGE}${VERSION}"* ]]; then ./test.sh; fi