---
docker_hub_namespace: &docker_hub_namespace ekino

# Common build_vars
CI_HELPER_VERSION: &CI_HELPER_VERSION 0.0.6
ci_helper_test: &ci_helper_test ci-helper version -e
MODD_VERSION: &MODD_VERSION 0.5

ansible:
  "2.5.5":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      VERSION: 2.5.5
    test_config:
      cmd:
        - *ci_helper_test
        - ansible --version
        - ansible-playbook --version
        - python --version

arachni:
  "1.5":
    build_args:
      ARACHNI_VERSION: 1.5.1
      ARACHNI_WEB_UI_VERSION: 0.5.12
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - arachni --version
        - *ci_helper_test

aws:
  "1":
    test_config:
      cmd:
        - aws --version
        - node --version
        - npm --version
        - pip --version
        - pip list | grep boto3
        - pip list | grep pyyaml
        - pipenv --version
        - *ci_helper_test
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 10.16.3-r0
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
      PY_YAML_VERSION: 3.13

awslnx-systemd:
  "2":
    template_vars:
      VERSION: 2.0.20190508
    test_config:
      cmd:
        - python --version
        - pip --version

azure:
  "2":
    build_args:
      AZURE_CLI: 2.0.72
      TERRAFORM_VERSION: 0.12.7
    test_config:
      cmd:
        - az --version
        - terraform --version

chrome:
  "1":
    build_args:
      MODD_VERSION: *MODD_VERSION
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - google-chrome --no-sandbox --version
        - google-chrome-unstable --no-sandbox --version
        - node --version
        - npm --version
        - yarn --version

dind-aws:
  "1":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      DOCKER_COMPOSE_VERSION: 1.25.0
      GLIBC_VERSION: 2.27-r0
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - docker --version
        - docker-compose --version

golang:
  "1.13":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      GLIDE_VERSION: v0.13.3
      MODD_VERSION: *MODD_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - go version
        - glide --version
        - gin --version
        - modd --version
    template_vars:
      GOLANG_VERSION: 1.13.5

java_test_config: &java_test_config
  cmd:
    - *ci_helper_test
    - java -version
    - mvn --version
    - aws --version
    - modd --version
    - dot -V
    - jq --version
    - psql --version

java:
  "8":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      VERSION: 8
      JAVA_VERSION: jdk8u232-b09-debian-slim
  "11":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
    test_config: *java_test_config
    template_vars:
      VERSION: 11
      JAVA_VERSION: jdk-11.0.5_10-debian-slim

kubectl:
  "1.16":
    test_config:
      cmd:
        - eksctl version
        - kube-score version
        - kubectx
        - kubeval --version
        - kustomize version
    build_args:
      EKSCTL_VERSION: 0.11.1
      KUBECTL_VERSION: 1.16.4
      KUBECTX_VERSION: 0.7.1
      KUBESCORE_VERSION: 1.4.0
      KUBEVAL_VERSION: 0.14.0
      KUSTOMIZATION_VERSION: 3.5.3

node_test_config: &node_test_config
  cmd:
    - *ci_helper_test
    - node --version
    - npm --version
    - yarn --version
    - sass --version
    - modd --version

node:
  "8":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 8.16.1
      NPM_VERSION: 6.12.0
      NVM_VERSION: 0.34.0
      MODD_VERSION: *MODD_VERSION
    test_config: *node_test_config
  "10":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 10.16.3
      NPM_VERSION: 6.12.0
      NVM_VERSION: 0.34.0
      MODD_VERSION: *MODD_VERSION
    test_config: *node_test_config
  "12":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      NODE_VERSION: 12.13.0
      NPM_VERSION: 6.12.0
      NVM_VERSION: 0.34.0
      MODD_VERSION: *MODD_VERSION
    test_config: *node_test_config

php_test_config: &php_test_config
  volume: php:/tmp
  cmd:
    - *ci_helper_test
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - security-checker --version
    - php /tmp/test.php

php:
  "7.2":
    build_args:
      APCU_VERSION: 5.1.18
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      COMPOSER_VERSION: 1.9.1
      MEMCACHED_VERSION: 3.1.4
      MODD_VERSION: *MODD_VERSION
      PHP_CS_FIXER_VERSION: 2.16.1
      REDIS_VERSION: 5.1.1
      SECURITY_CHECKER_VERSION: 6.0.3
      SSH2_VERSION: 1.2
      XDEBUG_VERSION: 2.8.0
    test_config: *php_test_config
    template_vars:
      PHP_VERSION: 7.2.25-cli-alpine
  "7.3":
    build_args:
      APCU_VERSION: 5.1.18
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      COMPOSER_VERSION: 1.9.1
      MEMCACHED_VERSION: 3.1.4
      MODD_VERSION: *MODD_VERSION
      PHP_CS_FIXER_VERSION: 2.16.1
      REDIS_VERSION: 5.1.1
      SECURITY_CHECKER_VERSION: 6.0.3
      SSH2_VERSION: 1.2
      XDEBUG_VERSION: 2.8.0
    test_config: *php_test_config
    template_vars:
      PHP_VERSION: 7.3.12-cli-alpine
  "7.4":
    build_args:
      APCU_VERSION: 5.1.18
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      COMPOSER_VERSION: 1.9.1
      MEMCACHED_VERSION: 3.1.4
      MODD_VERSION: *MODD_VERSION
      PHP_CS_FIXER_VERSION: 2.16.1
      REDIS_VERSION: 5.1.1
      SECURITY_CHECKER_VERSION: 6.0.3
      SSH2_VERSION: 1.2
      XDEBUG_VERSION: 2.8.0
    test_config: *php_test_config
    template_vars:
      PHP_VERSION: 7.4.0-cli-alpine

platformsh:
  "3.50":
    build_args:
      PLATFORMSH_CLI_VERSION: "3.50.1"
      PLATFORMSH_CLI_SHASUM: "d055e534fc71ce907a4111c55ce69e30ddb2dcc1b02aad7764d395872fc84e2e"
    test_config:
      cmd:
        - php --version
        - platform --version
        - python --version
        - pip --version

python:
  "2.7":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
    test_config:
      cmd:
        - *ci_helper_test
        - anchore-cli --version
        - pip --version
        - python --version
    template_vars:
      PYTHON_VERSION: 2.7.16
  "3.7":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
    test_config:
      cmd:
        - *ci_helper_test
        - pip --version
        - python --version
    template_vars:
      PYTHON_VERSION: 3.7.4

react-native:
  "2":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      MODD_VERSION: *MODD_VERSION
      NODE_VERSION: 12.13.0
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - node --version
        - npm --version
        - modd --version
        - react-native --version
        - rnpm --version
        - yarn --version

ruby:
  "2.6":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
    test_config:
      cmd:
        - bundle --version
        - *ci_helper_test
        - ruby --version

scoutsuite:
  "5.5":
    build_args:
      PIP_VERSION: 19.1.1
      PIPENV_VERSION: 2018.11.26
      SCOUTSUITE_VERSION: 5.5.0
    test_config:
      cmd:
        - pip --version
        - pipenv --version
        - scout --version

serverless:
  "1.59":
    build_args:
      PIP_VERSION: 19.2.1
      PIPENV_VERSION: 2018.11.26
      SERVERLESS_VERSION: 1.59.3
    test_config:
      cmd:
        - pip --version
        - python --version
        - node --version
        - npm --version
        - yarn --version
        - serverless --version
        - aws --version
    template_vars:
      NODE_MAJOR: 10

sonar:
  "3.3":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      GLIBC_VERSION: 2.27-r0
      SONARSCANNER_VERSION: 3.3.0.1492
    test_config:
      cmd:
        - *ci_helper_test
        - java -version
        - sonar-scanner -v

terraform:
  "0.12":
    build_args:
      TERRAFORM_VERSION: 0.12.18
    test_config:
      cmd:
        - terraform version
        - python --version
        - aws --version
