versions:
  "6.1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      SONARSCANNER_VERSION: 6.1.0.4477
    test_config:
      cmd:
        - java -version
        - sonar-scanner -v
