versions:
  "4.6":
    build_args:
      GLIBC_VERSION: 2.32-r0
      SONARSCANNER_VERSION: 4.6.2.2472
      ZLIB_VERSION: 1.2.11-3
    test_config:
      cmd:
        - java -version
        - sonar-scanner -v
