test_config: &test_config
  cmd:
    - terraform version
    - terragrunt --version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - infracost --version
    - az --version

versions:
  "0.13.7":
    build_args:
      TERRAFORM_VERSION: 0.13.7
      TERRAGRUNT_VERSION: 0.31.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.22
      INFRACOST_VERSION: 0.9.4
      AZURE_CLI_VERSION: 2.26.1
    test_config: *test_config
  "0.14.11":
    build_args:
      TERRAFORM_VERSION: 0.14.11
      TERRAGRUNT_VERSION: 0.31.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.22
      INFRACOST_VERSION: 0.9.4
      AZURE_CLI_VERSION: 2.26.1
    test_config: *test_config
  "0.15.5":
    build_args:
      TERRAFORM_VERSION: 0.15.5
      TERRAGRUNT_VERSION: 0.31.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.22
      INFRACOST_VERSION: 0.9.4
      AZURE_CLI_VERSION: 2.26.1
    test_config: *test_config
  "1.0.3":
    build_args:
      TERRAFORM_VERSION: 1.0.3
      TERRAGRUNT_VERSION: 0.31.1
      TERRAFORM_COMPLIANCE_VERSION: 1.3.22
      INFRACOST_VERSION: 0.9.4
      AZURE_CLI_VERSION: 2.26.1
    test_config: *test_config
