test_config: &test_config
  cmd:
    - terraform version
    - terragrunt --version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - infracost --version
    - az --version

versions:
  "0.13.7":
    build_args:
      TERRAFORM_VERSION: 0.13.7
      TERRAGRUNT_VERSION: 0.29.7
      TERRAFORM_COMPLIANCE_VERSION: 1.3.14
      INFRACOST_VERSION: 0.8.7
      AZURE_CLI_VERSION: 2.24.0
    test_config: *test_config
  "0.14.11":
    build_args:
      TERRAFORM_VERSION: 0.14.11
      TERRAGRUNT_VERSION: 0.29.7
      TERRAFORM_COMPLIANCE_VERSION: 1.3.14
      INFRACOST_VERSION: 0.8.7
      AZURE_CLI_VERSION: 2.24.0
    test_config: *test_config
  "0.15.4":
    build_args:
      TERRAFORM_VERSION: 0.15.4
      TERRAGRUNT_VERSION: 0.29.7
      TERRAFORM_COMPLIANCE_VERSION: 1.3.14
      INFRACOST_VERSION: 0.8.7
      AZURE_CLI_VERSION: 2.24.0
    test_config: *test_config
  "1.0.1":
    build_args:
      TERRAFORM_VERSION: 1.0.1
      TERRAGRUNT_VERSION: 0.31.0
      TERRAFORM_COMPLIANCE_VERSION: 1.3.21
      INFRACOST_VERSION: 0.8.7
      AZURE_CLI_VERSION: 2.24.0
    test_config: *test_config
