test_config: &test_config
  cmd:
    - terraform version
    - terragrunt --version
    - terraform-compliance --version
    - python --version
    - aws --version
    - git --version
    - infracost --version
    - az --version
    - gcloud --version

versions:
  "1.2.5":
    platforms: *base_platforms
    build_args:
      TERRAFORM_VERSION: 1.2.5
      TERRAGRUNT_VERSION: 0.38.5
      INFRACOST_VERSION: 0.10.8
    test_config: *test_config
