versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      HELM_DIFF_VERSION: 3.9.5
      HELM_VERSION: 3.14.4
      KUBECTL_VERSION: 1.29.4
      KUSTOMIZATION_VERSION: 5.4.1
      TRIVY_VERSION: "0.50.4"
      TERRAGRUNT_VERSION: "0.57.9"
      INFRACOST_VERSION: "0.10.35"
    test_config:
      cmd:
        - aws --version
        - git --version
        - helm diff version
        - helm version
        - kustomize version
        - pip --version
        - pipenv --version
        - trivy --version
        - zip --version
        - terragrunt --version
        - infracost --version
        - tfenv init
