versions:
  "1":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      DOCKER_COMPOSE_VERSION: 1.29.2
      GLIBC_VERSION: 2.27-r0
      PIP_VERSION: 21.2.1
      TRIVY_VERSION: "0.19.2"
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version
