versions:
  "1":
    build_args:
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      DOCKER_COMPOSE_VERSION: 1.25.0
      GLIBC_VERSION: 2.27-r0
      PIP_VERSION: 18.1
      PIPENV_VERSION: 2018.10.13
      AZURE_CLI_VERSION: 2.24.0
      TRIVY_VERSION: "0.16.0"
      TASKFILE_VERSION: *TASKFILE_VERSION
    test_config:
      cmd:
        - *ci_helper_test
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version
