versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config:
      cmd:
        - aws --version
        - az version
        - docker --version
        - docker-compose --version
        - task --version
        - trivy --version
