versions:
  "1":
    platforms:
      - linux/amd64
      - linux/arm64
    test_config:
      cmd:
        - google-chrome --no-sandbox --version
        - google-chrome-unstable --no-sandbox --version
        - node --version
        - npm --version
        - yarn --version
        - task --version
