test_config: &test_config
  cmd:
    - node --version
    - npm --version
    - aws --version
    - yarn --version
    - sass --version
    - modd --version
    - task --version

versions:
  "18":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 18.20.4
      NPM_VERSION: 10.9.0
      NVM_VERSION: 0.40.1
    test_config: *test_config
  "20":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 20.18.0
      NPM_VERSION: 10.9.0
      NVM_VERSION: 0.40.1
    test_config: *test_config
  "22":
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      NODE_VERSION: 22.11.0
      NPM_VERSION: 10.9.0
      NVM_VERSION: 0.40.1
    test_config: *test_config
