versions:
  "1.22":
    test_config:
      cmd:
        - kube-score version
        - kubectx
        - kubeval --version
        - kustomize version
        - helm version
        - aws --version
        - helmfile --version
        - helm diff version
    build_args:
      HELM_DIFF_VERSION: 3.1.3
      HELM_VERSION: 3.7.1
      HELMFILE_VERSION: 0.140.0
      KUBECTL_VERSION: 1.22.4
      KUBECTX_VERSION: 0.9.4
      KUBESCORE_VERSION: 1.13.0
      KUBEVAL_VERSION: 0.16.1
      KUSTOMIZATION_VERSION: 4.4.1
