versions:
  "1.22":
    test_config:
      cmd:
        - eksctl version
        - kube-score version
        - kubectx
        - kubeval --version
        - kustomize version
        - helm version
        - aws --version
        - helmfile --version
        - helm diff version
    build_args:
      EKSCTL_VERSION: 0.63.0
      HELM_DIFF_VERSION: 3.1.3
      HELM_VERSION: 3.6.1
      HELMFILE_VERSION: 0.140.0
      KUBECTL_VERSION: 1.22.1
      KUBECTX_VERSION: 0.9.4
      KUBESCORE_VERSION: 1.12.0
      KUBEVAL_VERSION: 0.16.1
      KUSTOMIZATION_VERSION: 4.2.0
