platforms: &platforms
  - linux/amd64
  - linux/arm64

test_config: &test_config
  cmd:
    - pip --version
    - python --version
    - aws --version
    - poetry --version

versions:
  "3.8":
    platforms: *platforms
    test_config: *test_config
  "3.9":
    platforms: *platforms
    test_config: *test_config
  "3.10":
    platforms: *platforms
    test_config: *test_config
  "3.11":
    platforms: *platforms
    test_config: *test_config
