test_config: &test_config
  cmd:
    - pip --version
    - python --version
    - aws --version

versions:
  "3.6":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.6.14
  "3.7":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.7.11
  "3.8":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.8.11
  "3.9":
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 3.9.6
