platforms: &platforms
  - linux/amd64
  - linux/arm64

test_config: &test_config
  volume: php:/tmp
  cmd:
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - php /tmp/test.php
    - aws --version
build_args: &build_args
  APCU_VERSION: 5.1.22
  COMPOSER_VERSION: 2.7.2
  MEMCACHED_VERSION: 3.2.0
  MODD_VERSION: *MODD_VERSION
  PHP_CS_FIXER_VERSION: 3.41.1
  REDIS_VERSION: 5.3.7
  XDEBUG_VERSION: 3.3.1
versions:
  "8.1":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
  "8.2":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
  "8.3":
    platforms: *platforms
    build_args:
      <<: *build_args
    test_config: *test_config
