test_config: &test_config
  volume: php:/tmp
  cmd:
    - *ci_helper_test
    - php --version
    - composer --version
    - modd --version
    - php-cs-fixer --version
    - security-checker -help
    - php /tmp/test.php

build_args: &build_args
  APCU_VERSION: 5.1.19
  CI_HELPER_VERSION: *CI_HELPER_VERSION
  COMPOSER_VERSION: 2.0.12
  ICONV_VERSION: 1.15-r3
  MEMCACHED_VERSION: 3.1.5
  MODD_VERSION: *MODD_VERSION
  MUSL_VERSION: 1.2.2-r0
  PHP_CS_FIXER_VERSION: 2.18.5
  REDIS_VERSION: 5.3.2
  SECURITY_CHECKER_VERSION: 1.0.0
  SSH2_VERSION: 1.2
  XDEBUG_VERSION: 3.0.3

versions:
  "7.2":
    build_args:
      APCU_VERSION: 5.1.19
      CI_HELPER_VERSION: *CI_HELPER_VERSION
      COMPOSER_VERSION: 2.0.8
      ICONV_VERSION: 1.15-r2
      MEMCACHED_VERSION: 3.1.5
      MODD_VERSION: *MODD_VERSION
      MUSL_VERSION: 1.1.24-r10
      PHP_CS_FIXER_VERSION: 2.18.0
      REDIS_VERSION: 5.3.2
      SECURITY_CHECKER_VERSION: 1.0.0
      SSH2_VERSION: 1.2
      XDEBUG_VERSION: 2.9.8
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.2.34-cli-alpine
  "7.3":
    build_args: *build_args
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.3.27-cli-alpine
  "7.4":
    build_args: *build_args
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 7.4.15-cli-alpine
  "8.0":
    build_args: *build_args
    test_config: *test_config
    template_vars:
      BASE_IMAGE_VERSION: 8.0.2-cli-alpine
